### ISSUE TITLE
404 from pycurl trying to reach https://packages.gitlab.com/gitlab/gitlab-ce/el/6Server/x86_64/repodata/repomd.xml

### ISSUE THREAD

**Issue by raids** [atomic-penguin/cookbook-yum-gitlab-ce#1] opened 2016-06-27 17:46 UTC
Hello

Nodes are receiving this error:

```
    * execute[yum clean metadata gitlab_gitlab-ce] action run
      - execute yum clean metadata --disablerepo=* --enablerepo=gitlab_gitlab-ce
    * execute[yum-makecache-gitlab_gitlab-ce] action run

      ================================================================================
      Error executing action `run` on resource 'execute[yum-makecache-gitlab_gitlab-ce]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce ----
      STDOUT:
      STDERR: https://packages.gitlab.com/gitlab/gitlab-ce/el/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
      Trying other mirror.
      To address this issue please refer to the below knowledge base article

      https://access.redhat.com/articles/1320623

      If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

      Error: Cannot retrieve repository metadata (repomd.xml) for repository: gitlab_gitlab-ce. Please verify its path and try again
      ---- End output of yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce ----
      Ran yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce returned 1

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/yum/providers/repository.rb

       69:   execute "yum-makecache-#{new_resource.repositoryid}" do
       70:     command "yum -q -y makecache --disablerepo=* --enablerepo=#{new_resource.repositoryid}"
       71:     action :nothing
       72:     only_if { new_resource.enabled }
       73:   end
       74:

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/yum/providers/repository.rb:69:in `block in class_from_file'

      execute("yum-makecache-gitlab_gitlab-ce") do
        action [:nothing]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "yum-gitlab-ce"
        only_if { #code block }
      end

      Platform:
      ---------
      x86_64-linux


    ================================================================================
    Error executing action `create` on resource 'yum_repository[gitlab_gitlab-ce]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[yum-makecache-gitlab_gitlab-ce] (/var/chef/cache/cookbooks/yum/providers/repository.rb line 69) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce ----
    STDOUT:
    STDERR: https://packages.gitlab.com/gitlab/gitlab-ce/el/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
    Trying other mirror.
    To address this issue please refer to the below knowledge base article

    https://access.redhat.com/articles/1320623

    If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

    Error: Cannot retrieve repository metadata (repomd.xml) for repository: gitlab_gitlab-ce. Please verify its path and try again
    ---- End output of yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce ----
    Ran yum -q -y makecache --disablerepo=* --enablerepo=gitlab_gitlab-ce returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/yum-gitlab-ce/recipes/default.rb

     19: yum_repository node['yum']['gitlab-ce']['repositoryid'] do
     20:   description node['yum']['gitlab-ce']['description'] unless node['yum']['gitlab-ce']['description'].nil?
     21:   baseurl node['yum']['gitlab-ce']['baseurl'] unless node['yum']['gitlab-ce']['baseurl'].nil?
     22:   enabled node['yum']['gitlab-ce']['enabled'] unless node['yum']['gitlab-ce']['enabled'].nil?
     23:   gpgcheck node['yum']['gitlab-ce']['gpgcheck'] unless node['yum']['gitlab-ce']['gpgcheck'].nil?
     24:   gpgkey node['yum']['gitlab-ce']['gpgkey'] unless node['yum']['gitlab-ce']['gpgkey'].nil?
     25:   sslcacert node['yum']['gitlab-ce']['sslcacert'] unless node['yum']['gitlab-ce']['sslcacert'].nil?
     26:   sslverify node['yum']['gitlab-ce']['sslverify'] unless node['yum']['gitlab-ce']['sslverify'].nil?
     27:   make_cache node['yum']['gitlab-ce']['make_cache'] unless node['yum']['gitlab-ce']['make_cache'].nil?
     28:   only_if { node['yum']['gitlab-ce']['managed'] }
     29:   action :create
     30: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/yum-gitlab-ce/recipes/default.rb:19:in `from_file'

    yum_repository("gitlab_gitlab-ce") do
      action [:create]
      updated true
      updated_by_last_action true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :yum_repository
      cookbook_name "yum-gitlab-ce"
      recipe_name "default"
      description "Gitlab CE"
      baseurl "https://packages.gitlab.com/gitlab/gitlab-ce/el/$releasever/$basearch"
      enabled true
      gpgkey "https://packages.gitlab.com/gpg.key"
      sslcacert "/etc/pki/tls/certs/ca-bundle.crt"
      sslverify true
      make_cache true
      repositoryid "gitlab_gitlab-ce"
      mode "0644"
      clean_metadata true
      only_if { #code block }
    end

    Platform:
    ---------
    x86_64-linux


Running handlers:
Running handlers complete
Chef Client failed. 2 resources updated in 07 seconds
```

I get the same thing on RHEL 6.7 & 7.2 (although they're going to their respective URLs of course).

I'm using the gitlab-ce cookbook (https://github.com/kemra102/gitlab-ce-cookbook).

Cheers
Raid

**Comment by atomic-penguin** [comment] 2016-08-17 16:21
@raids, any idea what the updated URL is, if it has changed?

**Comment by atomic-penguin** [comment] 2016-09-06 13:42
I cannot reproduce this.  It is possible you hit a transient error resolving the URL, or the service was down temporarily.

**Closed as completed by atomic-penguin** 2016-09-06 13:42 UTC
